sudo: required

language: node_js

node_js:
  - "node"

# services:
#   - docker

cache:
  yarn: true

notifications:
  email:
    on_failure: never
# env:
#   - DOCKER_COMPOSE_VERSION=1.20.1
#   # - DOCKER_COMPOSE_VERSION=1.4.2

stages:
  - name: Unit Tests Prod
    if: branch = master

  - name: Unit Tests
    if: branch = stage

  - name: deploy-prod
    if: branch = master

  - name: Deployment to qa
    if: branch = stage

jobs:
  include:
    - stage: Unit Tests Prod
      script: chmod +x .travis/test.sh && .travis/test.sh

    - stage: Unit Tests
      env:
        - API_URL=$API_URL_STAGE
      script: bash .travis/test.sh

      # - script: sh .travis/test.sh
      # name: "Integration Tests"
    - stage: deploy-prod
      script: echo 'deployment prod'

    - stage: Deployment to qa
      script: bash deployments/qa.sh
