# sudo: required

language: node_js

node_js:
  - "node"

# services:
#   - docker

cache:
  - bundler
  - yarn

notifications:
  email:
    on_failure: never
# env:
#   - DOCKER_COMPOSE_VERSION=1.20.1
#   # - DOCKER_COMPOSE_VERSION=1.4.2

stages:
  - name: Unit Tests Prod
    if: branch = master

  - name: Unit Tests
    if: branch = stage

  - name: deploy-prod
    if: branch = master

  - name: Deployment to qa
    if: branch = stage

jobs:
  include:
    # - stage: Unit Tests Prod
    #   script: bash .travis/test.sh

    - stage: Unit Tests
      env:
        - API_URL=$API_URL_STAGE
      script: bash .travis/test.sh

      # - script: sh .travis/test.sh
      # name: "Integration Tests"
    - stage: deploy-prod
      script: bash deployments/prod.sh
      before_deploy:
        - git config --global user.email "build@travis-ci.com"
        - git config --global user.name "Travis CI"
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: infra/*
        skip_cleanup: true
    - stage: Deployment to qa
      env:
        - API_URL=$API_URL_STAGE
      script: bash deployments/qa.sh
