# sudo: required

language: node_js

node_js:
  - "node"

# services:
#   - docker

cache:
  - bundler
  - yarn

notifications:
  email:
    on_failure: never
# env:
#   - DOCKER_COMPOSE_VERSION=1.20.1
#   # - DOCKER_COMPOSE_VERSION=1.4.2

stages:
  - name: Unit Tests Prod
    if: branch = master

  - name: Unit Tests
    if: branch = stage

  - name: deploy-prod
    if: branch = master

  - name: Deployment to qa
    if: branch = stage

jobs:
  include:
    # - stage: Unit Tests Prod
    #   script: bash .travis/test.sh

    - stage: Unit Tests
      env:
        - API_URL=$API_URL_STAGE
      script: bash .travis/test.sh

      # - script: sh .travis/test.sh
      # name: "Integration Tests"
    - stage: deploy-prod
      after_success:
        - sh deployments/prod.sh

      # script: bash deployments/prod.sh
    - stage: Deployment to qa
      env:
        - API_URL=$API_URL_STAGE
      script: bash deployments/qa.sh
