version: "3"

services:
  wordpress:
    depends_on:
      - mysql
    env_file:
      - ./docker.env
    image: wordpress:4.9.8
    restart: always
    # ports:
    #   - "5000:9000"
    expose:
      - "5000"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: asesor
      # WORDPRESS_TABLE_PREFIX: asesorvn_
    volumes:
      - ./wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    env_file:
      - ./docker.env
    volumes:
      # - ../../../volumes/carros:/var/lib/mysql
      - ../../volumes/carros:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      # MYSQL_DATABASE: wp_1
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: wordpress
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0

  web:
    build: ./web
    restart: always
    # volumes:
    #   - ./web:/app
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"

  proxy:
    build: .
    depends_on:
      - wordpress
      - web
    restart: always
    volumes:
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
