const routes = require('next-routes')

// .add(nombre, url, archivo.js)
// .add('channel', '/:slug.:id', 'channel')
module.exports = routes()
  .add('index')
  // .add('podcast', '/:slugChannel.:idChannel/:slung.:id', 'podcast')
  .add('articulos', '/articulos', 'articulos')
  .add('articulo', '/articulos/:name', 'articulo')
  .add('tags', '/tags', 'tags')
  .add('tag', '/tags/:slug', 'tag')
  .add('entradasIndex', '/vehiculos', 'index')
  .add('entradas', '/vehiculos/:slug', 'entradas')
  .add('entradasMarcas', '/vehiculos/:slugMarca/:slugModelo', 'entradas')
  .add('entrada', '/:name', 'entrada')
